// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAocwQS4jfAHmmHPlmbf7g5_EQ56t9l-2Y',
    appId: '1:556674368583:web:9fbb4a307ab498e0665d62',
    messagingSenderId: '556674368583',
    projectId: 'flutter-app-distribution-a3dfb',
    authDomain: 'flutter-app-distribution-a3dfb.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-a3dfb.appspot.com',
    measurementId: 'G-8WDSJC745E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjaa7S60tYVWIED5vxSV7R9QW8H797DiM',
    appId: '1:556674368583:android:7272e5d6884c6967665d62',
    messagingSenderId: '556674368583',
    projectId: 'flutter-app-distribution-a3dfb',
    storageBucket: 'flutter-app-distribution-a3dfb.appspot.com',
  );

}