# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase app Destribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
            app: "1:556674368583:android:7272e5d6884c6967665d62",
            firebase_cli_token: "1//03iL_QMf-SzGFCgYIARAAGAMSNwF-L9IrVrB4QUk91F-8Uyaait89RrjfGLhYFmB-tZir9A1QLHzxPQiJIFIVsx0oINuoyJ2wE00",
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
            testers: "ibrahim13elgammal@gmail.com",
            release_notes: "First fastlane firebase distribtuion for me"
        )
  end
end
